### PR TITLE
Test harder.

### PR DESCRIPTION
**Pull request by Lemmih**
Test once with 10,000 runs, once with a data size of 10,000, and once with 1,000 runs and a data size of 1,000.
I've also included a pass that checks the syntax of the haddock documentation.

#33

### CODE REVIEW

**Comment by treeowl** [comment]
Great! Thanks so much again! I'll merge as soon as the tests pass.

**Comment by treeowl** [comment]
Er.... Actually.... My recollection when I did this manually was that the arguments needed to be applied to a *specific* test target. Is that wrong?

**Comment by Lemmih** [comment]
The options are applied to all test targets unless otherwise specified.

**Comment by treeowl** [comment]
Guess I got that wrong. Cool.

**Comment by treeowl** [comment]
Do you want to squash selectively, or should I apply a big hammer?

**Comment by Lemmih** [comment]
> Guess I got that wrong. Cool.

It may have changed with the new commands. The new v2 commands are a huge improvement over the old ones.

**Comment by Lemmih** [comment]
> Do you want to squash selectively, or should I apply a big hammer?

Big hammer, please. The patch history isn't important.

**Comment by treeowl** [comment]
Thanks again.

**Pull request merged**
