### PR TITLE
Basic test scaffold using tasty and quickcheck.

### PR DESCRIPTION
**Pull request by Lemmih**

### CODE REVIEW

**Comment by treeowl** [comment]
The whole `NoStarIsType` thing is just left over from my development process. We don't actually need it at all....

**Comment by Lemmih** [comment]
Hm, a Windows box failed with a segfault while installing dependencies. Not sure why that would happen.

**Comment by treeowl** [comment]
Interesting, but clearly not our problem.

**Comment by treeowl** [comment]
Thanks! And good choice for an initial test.

**Pull request merged**
