### PR TITLE
Build and run testsuite as a github action

### PR DESCRIPTION
**Pull request by Lemmih**
GHC versions tested: 8.6.5, 8.8.3, and 8.10.1.
Platforms: linux, macos, and windows.

### CODE REVIEW

**Comment by Lemmih** [comment]
Btw, the library fails to build with GHC version 8.4.4 because of missing support for the NoStarIsType extension.

**Comment by treeowl** [comment]
That's a pain. But where are the test results, or do I need to enable something for the repository first?

**Comment by Lemmih** [comment]
The tests will only be run once the workflow file has been committed to 'master'. Afterwards, the workflow file in 'master' will be used to test all new PRs.

**Comment by treeowl** [comment]
Could you please squash?

**Comment by Lemmih** [comment]
You have a button for squashing the PR to a single commit, right? I don't mind if you squash it.

**Pull request merged**
